---
title: "Coding Style"
---

Generally we use the [`tidyverse` style guide](https://style.tidyverse.org/) to ensure our code is consistent. The `lintr` and `styler` packages can help make this easier:

-   `lintr`: You can use the 'Lint current file' command in the 'Addins' menu in R Studio to obtain a list of all the places your script doesn't comply with the style guide. You can then change your code to comply.

-   `styler`: The 'Style active file' command (also accessed through the Addins menu) or 'Ctrl+Shift+A' will do some of these changes for you. However, it is worth rerunning `lintr` afterwards to check any remaining issues.

There are a few instances when we vary from the `tidyverse` style guide for our own needs, which are laid out below:

1.  We explicitly call packages rather than loading them.

    > Do:
    >
    > `dplyr::select(...)`
    >
    > Don't:
    >
    > `library(dplyr)`
    >
    > `select(...)`

2.  We document our functions using [roxygen](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html).

    **All tags should be explicitly specified.**

    **We should include at a minimum the `@description`, `@param` and `@return` tags.**

    If used, @title should be the name of the function. @examples and @seealso can also be useful.

    **Tip:** You can get an automatic roxygen skeleton for a function in R Studio through 'Code \> Insert Roxygen Skeleton' or by pressing *Ctrl + Alt + Shift + R*.

    Below is an example of a well documented function:

    **ADD THIS**
