---
title: "Documentation Library"
output: 
  html_document:
    css: style.css
---

The below sets out the full set of documentation for LAPCAP, alongside where it can be found. In some cases, it may be stored in multiple locations and care should be taken to ensure both copies remain up to date.

In general, documentation should be kept as close to the code as possible, for ease of access. However, this may not always be possible.

# Overarching Documentation

|  |  |  |
|------------------------|------------------------|------------------------|
|  | Description | Location |
| Model Development Plan | A plan for model development, quality assurance and signoff processes. | [LAPCAP Model Development Plan](https://defra-pepr-modelling-team.github.io/module_b_team_pages/lapcap_bible.html) |
| Signoff Log | Log of signoffs obtained for each version of LAPCAP. | [03 LAPCAP Signoff Log](https://defra.sharepoint.com/:x:/r/teams/Team1478/_layouts/15/Doc.aspx?sourcedoc=%7B5065D966-5D34-493C-92E1-FCA1CE67B2FD%7D&file=TEMPLATE%20modulename%20assumptions_data_log1.xlsm&action=default&mobileredirect=true) |
| FPC Team Pages | Detailed practical steps required for various team processes. Model development plan is stored here also. | [FPC Team Pages](https://defra-pepr-modelling-team.github.io/module_b_team_pages/index.html) |

There are also templates for:

-   Assumptions logs ([TEMPLATE modulename assumptions_log.xlsm](https://defra.sharepoint.com/:x:/r/teams/Team1478/Extended%20Producer%20Responsibility%20for%20Packaging/07%20Fees%20and%20Payments%20Calculator/18%20Module%20B1%20-%20LA%20FNCs/04%20Bottom-up%20Modelling/00%20Model%20Master/TEMPLATE%20modulename%20assumptions_log.xlsm?d=wb9cab66a483648f68e962eee10eb1add&csf=1&web=1&e=7kzgb7))
-   Change logs ([TEMPLATE model output sensitivity testing.xlsx](https://defra.sharepoint.com/:x:/r/teams/Team1478/Extended%20Producer%20Responsibility%20for%20Packaging/07%20Fees%20and%20Payments%20Calculator/18%20Module%20B1%20-%20LA%20FNCs/04%20Bottom-up%20Modelling/00%20Model%20Master/TEMPLATE%20model%20output%20sensitivity%20testing.xlsx?d=w2f17d9953c16471d846b3fa3a97fd816&csf=1&web=1&e=itEbIe))
    -   Used to check changes in outputs for each merge.
-   Verification logs ([TEMPLATE verification log.xlsx](https://defra.sharepoint.com/:x:/r/teams/Team1478/Extended%20Producer%20Responsibility%20for%20Packaging/07%20Fees%20and%20Payments%20Calculator/18%20Module%20B1%20-%20LA%20FNCs/04%20Bottom-up%20Modelling/00%20Model%20Master/TEMPLATE%20verification%20log.xlsx?d=w211af91668db4e89ae63b12812c6a30e&csf=1&web=1&e=CFfKY0))
    -   Used by our quality assurance lead (Peter Neary) to keep a record of verification being done for each merge.

# Version Specific Documentation

In the [00 Model Master](https://defra.sharepoint.com/:f:/r/teams/Team1478/Extended%20Producer%20Responsibility%20for%20Packaging/07%20Fees%20and%20Payments%20Calculator/18%20Module%20B1%20-%20LA%20FNCs/04%20Bottom-up%20Modelling/00%20Model%20Master?csf=1&web=1&e=nb7fDx) folder, each model version will have a folder. This will contain all the documentation specific to that version. 

Whilst the version is still under development this folder will have “- IN PROGRESS” appended to its name. 

Once the version is completed (i.e. tagged on Github), the folder will have the “- IN PROGRESS” label removed, a zip file of the code and a copy of the model outputs saved into it and should not be edited from that point onwards. 

Instead, a new “- IN PROGRESS” folder should be created, with below documents from the previous version copied into it, that can then be edited alongside changes to the code for the new version. 

|  |  |
|------------------------------------|------------------------------------|
|   | Description  |
| Technical Document  |  A full description of the model including code maps and example calculations. Should be detailed enough to allow for an external to recreate the model.  |
| Assumptions Logs  |  A record of assumptions we have made throughout the model.  |
| Data Logs  |  A record of data inputs used by LAPCAP.  |
| User Guide  | Guidance on how to practically run and control LAPCAP.  Stored in the README file in our GitHub repository.  |
| Change Log  | A record of changes in output numbers for merges between versions.  |
| Verification Log  | A record of verification done on each merge. Maintained by our quality assurance lead (Peter Neary).  |
