---
title: "Module B2 - Binned Waste"
---

The Module B2 Binned Waste team is responsible for developing a model to estimate local authorities' costs of collecting and disposing of packaging placed in street bins. 

Producers will then be required to pay these costs which will incentivise them to reduce packaging waste and make packaging more recyclable.

This brings many benefits including greater resource efficiency, reduced pollution and reduced carbon emissions, supporting nature and combatting climate change.

 Name | Areas of Work | Location | Working Pattern | Preferred Communication Method | Tips for Working Together | 
|---|---|---|---|---|---|
| Jake Billingham | Team Lead | Usually London office Mon - Thur, at home in North London on Friday | Mon - Fri, 9:30 - 5:30 | In person > Teams message > Email (but use email for anything we may need a record of) | Don't put meetings over Wednesday table tennis! |
| Ope Ojo  | Coding Expert | London office Wednesdays and either Tuesday or Thursday | Mon - Fri, 9:30 - 5:30 | Whichever is best for the context |  |  |
| Jo Keegan | Readiness Lead |  Working from home in Staffordshire | Mon - Thu, 8 - 5:30/6 | Whichever is best for the context |  |
| Clare Watson | Policy Lead | Bristol office 4 days a week | Mon - Fri, 9:30 - 5:30  | Whichever is best for the context |  |
| Bim Chaloner | ? | ? |  ? | ? | ? |

**New joiners:** Let Jake know and he can add your details!